### ISSUE TITLE
support for RD9700 chipset

### ISSUE THREAD

**Issue by Rolf-L** [analogdevicesinc/buildroot#33]
In ADALM-Pluto I'm missing a Linux Driver for the RD9700 chipset. This chipset is used in many cheap USB-Ethernet adapters

**Comment by mhennerich** [comment]
It doesn't look like there is a in tree kernel driver for the RD9700, however there is some evidence that the DM9601 driver can be used.
https://elinux.org/RPi_USB_Ethernet_adapters
I think I have some of these devices and the performance isn't great...
 Can you plug your device into a desktop Linux box or RPi and send me the dmesg?

**Comment by Rolf-L** [comment]
Hi Michael,
thanks a lot for your infos.
Meanwhile, I ordered a USB 3.0 adapter and hope that it works on the USB-port of my ADALM-Pluto.

**Comment by mhennerich** [comment]
Hi,

please take a look here:
https://wiki.analog.com/university/tools/pluto/usb_otg_host_function_support

The RTL8153 based adapters are a good choice.
