### ISSUE TITLE
buildroot make failure

### ISSUE THREAD

**Issue by MrChen531** [analogdevicesinc/buildroot#35]
make -C buildroot TOOLCHAIN_EXTERNAL_INSTALL_DIR= ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- BUSYBOX_CONFIG_FILE=/buildroot/board/pluto/busybox-1.25.0.config all 

ERROR INFO：
relocation R_X86_64_PC32 against symbol `_nc_user_definable' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:2864: recipe for target 'libgettextlib.la' failed
make[4]: *** [libgettextlib.la] Error 1
make[4]: Leaving directory '/home/cl/Documents/plutosdr-fw/buildroot/output/build/host-gettext-0.19.8.1/gettext-tools/gnulib-lib'
Makefile:2614: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/cl/Documents/plutosdr-fw/buildroot/output/build/host-gettext-0.19.8.1/gettext-tools/gnulib-lib'
Makefile:2023: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/cl/Documents/plutosdr-fw/buildroot/output/build/host-gettext-0.19.8.1/gettext-tools'
Makefile:1889: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/cl/Documents/plutosdr-fw/buildroot/output/build/host-gettext-0.19.8.1/gettext-tools'
package/pkg-generic.mk:238: recipe for target '/home/cl/Documents/plutosdr-fw/buildroot/output/build/host-gettext-0.19.8.1/.stamp_built' failed
make: *** [/home/cl/Documents/plutosdr-fw/buildroot/output/build/host-gettext-0.19.8.1/.stamp_built] Error 2
make: Leaving directory '/home/cl/Documents/plutosdr-fw/buildroot'

This is the message that make buildroot failed, I don't know what went wrong, hope to help solve it.

**Comment by MehdiJaiem502** [comment]
I don't know if it's the same error but I got this one after 10 minutes of compilations
`mv: cannot move '/home/mehdi/buildroot/output/build/toolchain-external-arm-arm-2018.11/arm-linux-gnueabihf' to 
'/home/mehdi/buildroot/output/host/opt/ext-toolchain/arm-linux-gnueabihf': Permission denied 
package/pkg-generic.mk:168: recipe for target '/home/mehdi/buildroot/output/build/toolchain-external-arm-arm-2018.11/.stamp_extracted' failed make: *** 
[/home/mehdi/buildroot/output/build/toolchain-external-arm-arm-2018.11/.stamp_extracted] Error 1`

**Comment by tfcollins** [comment]
@MehdiJaiem502 can you provide more context to what stage your build is failing at?

Also what tool versions are you using for compiling?

**Comment by MehdiJaiem502** [comment]
Hello


Well I Finally figured it out although it wasn't obvious at all.

So I had to upgrade my WSL to WSL2 and compile and make everything the normal way as stated in Buildroot guide for STM32MP157C-DK2:

https://bootlin.com/blog/building-a-linux-system-for-the-stm32mp1-basic-system/


I was using Ubuntu 18.04 on Windows WSL.

________________________________

**Comment by commodo** [comment]
We typically build this repo on Linux.
Building (or cross-building) on Windows WSL + Ubuntu is more in the scope of buildroot support.
i.e. here https://github.com/buildroot/buildroot
